spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/shopping_cart
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  sql:
    init:
      mode: always