analyzer.kafka.bootstrap-servers=localhost:9092

analyzer.kafka.topic.snapshots=telemetry.snapshots.v1
analyzer.kafka.topic.hubs=telemetry.hubs.v1

analyzer.kafka.consumer.snapshots.group-id=analyzer-snapshots
analyzer.kafka.consumer.hubs.group-id=analyzer-hubs

spring.datasource.url=jdbc:postgresql://localhost:5432/analyzer
spring.datasource.username=analyzer
spring.datasource.password=analyzer

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.sql.init.mode=always

grpc.client.hub-router.address=static://localhost:59090
grpc.client.hub-router.enableKeepAlive=true
grpc.client.hub-router.keepAliveWithoutCalls=true
grpc.client.hub-router.negotiationType=plaintext